#ifndef TASKMANAGER_GLOBAL_H
#define TASKMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TASKMANAGER_LIBRARY)
#  define TASKMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TASKMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TASKMANAGER_GLOBAL_H
